### ISSUE TITLE
Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by kariot** [WaveTechStudio/SMSRetrieverAPIMaster#2]
When the activity is minimized an error has occurred which causes an issue while resuming the activity
The error in console is :

Activity <full to activity> has leaked IntentReceiver <package>.SMSReceiver@e89a096 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity <full to activity> has leaked IntentReceiver <package>.SMSReceiver@e89a096 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by mreram** [comment]
I have sent a pull request for this issue. #3

**Comment by kariot** [comment]
Fixed with the below code

 @Override
    protected void onStop() {
        super.onStop();
        if (smsReceiver != null) {
            this.unregisterReceiver(smsReceiver);
        }
    }
    @Override
    protected void onStart() {
        super.onStart();
        startSMSListener();
    }

**Comment by WaheedNazir** [comment]
Thanks.
