### ISSUE TITLE
How to get hash key for signed apk? This auto fetching is not working after app is live on playstore. Please help how can i get hash key for signed apk from appSignatureHashHelper?

### ISSUE THREAD

**Issue by ZakiResoluteSolutions** [WaveTechStudio/SMSRetrieverAPIMaster#4]
String hashkey = appSignatureHashHelper.getAppSignatures().get(0); 

I am using this for normal hash key

**Comment by ZakiResoluteSolutions** [comment]
Will you please help me for this as soon as possible?

**Comment by ZakiResoluteSolutions** [comment]
I got the solution from

**Comment by WaheedNazir** [comment]
Hello @ZakiResoluteSolutions you can add a dialog into signed apk and display this hashkey in dialog message.

String hashkey = appSignatureHashHelper.getAppSignatures().get(0);

Then you can note down and share it with your server. Later on remove dialog and make signed apk for your use. Keep in mind when you change package id of your app your hashkeys would be changed for debug/signed apks.

**Comment by ZakiResoluteSolutions** [comment]
Thank you so much.
