### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by nizarGannouni** [WaveTechStudio/SMSRetrieverAPIMaster#5]
I highly value this interesting effort,
what I did not understand the following actions:
-App request your server to verify the entered mobile number.
-Your app calls the SMS Retriever API at the same time and listening for an SMS from your server.
-Your server sends an SMS message that includes a verification code and a hash to identify your app.

Does this mean that I have to write a php script in my server? how?
cordially

**Comment by WaheedNazir** [comment]
Yes any backend script can work, or if your app is using firebase you can implement this easily firebase automatically provides this.
